### ISSUE TITLE
Student's Name using CEDS

### ISSUE THREAD

**Issue by philbarker** [pesc-org/json-ld-transcript#15]
We already use `ceds:hasOtherPersonName` and `ceds:hasPersonName` as direct equivalents of PESC terms.

The CEDS draft ontology uses two different classes for objects of these properties, PersonName and PersonOtherName, with a set subtype of PersonOtherName.

Proposed mapping:
| PESC                      | CEDS                   |
|---------------------------|----------------------------|
| nameCode              | `@type`(?)
| namePrefix             | ceds:PersonalTitleOrPrefix
| firstName                | ceds:FirstName
| middleName           | ceds:MiddleName
| lastName                | ceds:LastOrSurname
| nameSuffix             | ceds:GenerationCodeOrSuffix
| nameTitle               | ceds:PersonalTitleOrPrefix
| compositeName     | 

For compositeName we could either:
- create a PESC property compositeName
- use schema.org/name
- use foaf:name

| PESC Name codes | CEDS Classes        |
|----------------------------------------|----------------------------------------|
| Casual                     | 
| Formal                     | 
| Former                    | ceds:PersonOtherName_PreviousLegalName
| LawSchoolApplicationSource |
| Legal                       | 
| MedicalSchoolApplicationSource |
| Nickname               | ceds:PersonOtherName_Nickname
| Other                      | ceds:PersonOtherName

**Comment by philbarker** [comment]
Problems with this mapping

* There are errors in the draft CEDS Ontology around PersonOtherName
* CEDS do not list any properties for the PersonOtherName or its subclasses in the draft ontology
  * the elements like `Other First Name` are not in the draft
* The CEDS Other Name classes provide only patchy coverage of current PESC name codes  
  *  The CEDS ontology only covers CEDS core elements, not extended elements like NameCode

Need to decide:
* what to do for composite name.
* whether to use CEDS PersonOtherName or stick with PESC name codes.

**Comment by 4pins** [comment]
If CEDS resolves their issue, I say stay with them.  If not feel free to change.

**Comment by philbarker** [comment]
compositeName is a legacy field, not widely used. Probably doesn't matter much. 

displayName would be more useful (optional). Could use full name from CEDS.

Ought to take this higher before implementing.

Keep compositeName for now, as pesc: property.

Probably ought to expand enumeration to include things like preferredName.
