### ISSUE TITLE
Phone / FAX

### ISSUE THREAD

**Issue by philbarker** [pesc-org/json-ld-transcript#19]
We have

```mermaid
graph LR
C(Contact) -- phone --> P(Phone)
C -- faxPhone --> P
```
We break the telephone number down into parts (country prefix, area code, number, extension)

CEDS draft Ontology has 
* a Class Telephone with subclasses OrganizationTelephone and PersonTelephone, each with various subclasses of their own, including for faxes.
* a property to connect an Organization to a Telephone, 
* a single property for telephone number

As far as I can see CEDS draft ontology
* has no property  to connect a Person to a Telephone 

CTDL (which we use for the other contact details) has telephone and fax as properties of ContactPoint (so no class for Telephone / FAX details), with simple strings as the expected value.

### Mapping ###
| PESC | CEDS | CTDL | Note |
|----|----|----|---|
| pesc:Phone | Telephone or Fax | |
| pesc:expirationDate | RecordEndDateTime | | |
| pesc:attentionLine | | | Moved to ContactPoint |
| pesc:countryPrefixCode
| pesc:areaCityCode
| pesc:phoneNumber
| pesc:phoneNumberExtension
| | TelephoneNumber | telephone or faxNumber

### Possibilities  ###
To keep the breakdown of the phone number (which seems useful): use the CTDL properties to link ContactPoint to an object with type drawn from CEDS, and keep the PESC properties to specify the number.

Or

Simplify, don't bother with the breakdown of the phone number, and just use CTDL properties in the ContactPoint.

**Comment by 4pins** [comment]
Unsurprisingly we are more similar to CEDS.

http://specification.sifassociation.org/Implementation/NA/4.3/CommonTypes.html#obj:PhoneNumberType

FYI

**Comment by philbarker** [comment]
Keep country code and extension.
Combine area code and phone number into one, call it: `phoneNumber`, and make sure definition gets changed to reflect this.

No need for expiration date as have start and end date for contact.

Should consider relevance of phone numbers in the long term, but definitely keep it as part of transcript.
