### ISSUE TITLE
Mapping Organization to CEDS

### ISSUE THREAD

**Issue by philbarker** [pesc-org/json-ld-transcript#21]
CEDS has several subclasses for Organization, we currently have just one top-level organization.

Most of the properties of Organization are identifiers or related to contact details.

Contact we have pretty much solved for Person using CTDL in such a way that we can use the same object type for Organization.

For identifiers we can try the same CEDS-based approach as we did for person identifiers: instead of separate properties for each type of identifier, we use the `ceds:hasOrganizationIdentification` property with an object of relevant the type. 

That leaves just a handful of properties: `accreditation`, `noteMessage`/`elm:additionalNote`, `organizationName`, `schoolLevel`, `schoolOverrideCode`.

### List of most relevant CEDS Organization subclasses
AdultEducationProvider
CredentiallingOrganization
EarlyCollege
EducationInstitution
K12School
PostsecondaryInstitution
PostsecondarySystem
(and several other more specialized types).

- [x] Do we want to use these types instead of broader `ceds:Organization` type?

### Contact Point
We found CEDS addresses to be problematic for Students (they were [too US-centric](https://github.com/philbarker/transcript_jsonld/issues/12)) and so [used CTDL](https://github.com/pesc-org/json-ld-transcript/issues/5) ContactPoint + PostalAddress instead.

- [x] Shall we use ceterms:ContactPoint for organizations as well?

### Identifier mapping
If we use CEDS for identifiers as we did with Person, here are the relevant types of identifier.

| PESC Identifier | CEDS Identifier Type | CEDS Description
|---------------------|------------------------------|-------------------------|
| pesc:actID | OrganizationIdentification_ACT | College Board/ACT program code set of PK-grade 12 institutions
| pesc:atpID | 
| pesc:ccdID | 
| pesc:ceebactID |
| pesc:csisID |  [Canadian, old, not in CEDS] |
| pesc:dunsID | OrganizationIdentification_DUNS | Dun and Bradstreet number
| pesc:esisID |  [Canadian, old, not in CEDS] |
| pesc:ipedsID |
| pesc:ficeID |
| pesc:nchelpID |
| pesc:opeID |
| pesc:psisID | [Canadian, not in CEDS] |
| pesc:pssID |
| pesc:usisID |  [Canadian, old, not in CEDS] |
| pesc:localOrganizationID | 
| pesc:mutuallyDefinedID | OrganizationIdentification_Other | Not yet defined in CEDS.

CEDS has others, see [element/000827](https://ceds.ed.gov/element/000827), [element/001072](https://ceds.ed.gov/element/001072).

Any others that we don't match would likely be handled using the CEDS _Other or _OtherFederal + a type from the pesc: namespace.

### Remaining properties

| Pesc property | Mapping |
|-------------------|--------------|
| accreditation | ceds:AccreditingOrganization
| noteMessage | elm:additionalNote or drop
| organizationName | ceds:NameOfInstitution
| schoolLevel | ? Maybe Organization subtype?
| schoolOverrideCode |

- [x] Need more information on school level and school override code.
- [x] Do we keep note/message?

**Comment by philbarker** [comment]
model identifiers as was done for PersonIdentification
rm: schoolOverrideCode
Keep with Organization rather more specific types
Keep current school levels

**Comment by philbarker** [comment]
On 28 Feb, decided that OpeID and PSIS were suggested as the most important organization id schemes for US and Canada respectively. [OpeID is in CEDS Domain Entity Schema](https://ceds.ed.gov/element/000203) but under "Directory" and [not as an identification scheme](https://ceds.ed.gov/element/000827), and is not in the draft ontology.  CTDL, incidently, has a property for [opeID](https://purl.org/ctdl/terms/opeID).

PSIS, being non-US is not in CEDS.

I suggest, for now, creating identifier types in the pesc: namespace for OPEID and PSIS.

**Comment by 4pins** [comment]
"I suggest, for now, creating identifier types in the pesc: namespace for OPEID and PSIS."
Seems right to me!
