### ISSUE TITLE
Mapping Test, RAP and Language Shapes

### ISSUE THREAD

**Issue by philbarker** [pesc-org/json-ld-transcript#40]
# Test shape

A possible match in CEDS is C200010 Assessment, and in Credential Engine is [AssessmentProfile](https://credreg.net/ctdl/terms#AssessmentProfile).

Properties:

| PESC                          | CEDS                                             | CTDL                        |Notes                        |
|-----------------------------|---------------------------------------------|----------------------------|----------------------------|
| testCode                   | ? P001067 AssessmentIdentifier | identifier             | What are the allowed values? |
| educationTestCode | ?                                                     |                                 | What are the allowed values? |  
| testName                 | P000028 AssessmentTitle         | name    | Allowed values? [1] 
| testDate                    | P001544 AssessmentRevisionDate | date      | or property of achievement? [2] |
| testYearMonth        ||| property of achievement? [2] |
|  testYear                   |||property of achievement? [2] |
| subTest                     | [3]  | hasPart ||

1. CEDS also has AssessmentShortName, __FamilyTitle & __FamilyShortName. Examples of assessment families (short names) are Graduate Record Exam (GRE) or National Assessment of Educational Progress (NAEP).
2.  Are these the date the student took the test, or is a test set in a particular year, or both?
3. CEDS has a class of AssessmentSubTest, but it is not clear how to relate a Subtest and Assessment

# RAP Shape

Would it be correct to characterize RAPs as being Competencies? If so we could use CEDS C200065 Competency Definition or CTDL ASN [Competency](https://credreg.net/ctdlasn/terms/Competency)

A Competency Definition in CEDS is

>  A resource that states a capability or behavior that a person may learn or be able to do within a given context with references to potential levels of competence, a mastery threshold, and other contextualizing metadata.

Properties:

| PESC                          | CEDS                                             | CTDL ASN                       |Notes                        |
|----------------------|---------------------------------------------|----------------------------|----------------------------|
| rapCode           | P000692 Competency Definition Code | codedNotation |[1]|
| rapName         | P001409  Competency Definition Short Name | competencyLabel |
| rapSubName  | |||

Is the definition recorded anywhere?

# Language

CEDS C200293 Person Language seems like a good match. CTDL just uses language codes.

Properties:

| PESC                             | CEDS                                           | Notes                        |
|--------------------------------|---------------------------------------------|----------------------------|
| languageCode            |  P000317 Has ISO 639-2 Language Code | Do you use ISO lang codes? |
| languageProficiency |
| languageUsage         | P000316 Has Language Type | See code mapping below |

## Language usage codes
| PESC language usage: | [CEDS languge type](https://ceds.ed.gov/element/000316)  |
|--------------------------------|---------------------------------|
| FirstSpokenlanguage | NI000316151876 Dominant language |
| Native                           | NI000316151874 Native language |
| Reading ||
| Speaking | #NI000316151877 Spoken Correspondence |
| SpokenAtHome | NI000316151875 Home language |
| Writing ||
| WrittenCommunication | NI000316151878 Written Correspondence | 
| |  Other |
| |  Other language proficiency |
| | Correspondence |

**Comment by Statfan13** [comment]
The testCode values in the PESC standard are found in Appendix D, which is at the end of the XML Implementation Guide.  I will email that section to you in case you don't have the IG.

educationTestCode values are in Appendix E

testName are in Appx D nor E, although I can look through the list for CEDS and see how much of it matches.  It's just a name

test Date and YearMonth are the date the student took the test

rapCode is "Requirement (or attribute or proficiency) demonstrated or earned by completio0n of this course, in addition to or as part of an academic award".

languageCode is indeed the ISO 639-2 code set

I think your mapping of the language usage codes looks good

**Comment by philbarker** [comment]
Notes from 25 Sep call.

Keep rap properties in pesc: namespace.
Use CEDS Competency properties for Requirements and Proficiencies;
Attributes are attributes of course, not of person, e.g. is it taught in a computer lab, so needs its own object type.


For Test names and codes, the allowed values are not something that PESC is likely to be maintaining as part of the Transcript spec., so don't try to validate via an enumeration in the schema.

Remove date-related properties to test results

OK to reference as an Assessment and not something more explicitly related to standard tests.

Sub Tests can treated same as tests. The same assessment can be used alone or as a subtest.

**Comment by philbarker** [comment]
To do:
- [ ]  TestShape to use ceds: Assessment class and properties.
  - [ ] Diagram
  - [ ] TAP
  - [ ] Tests
- [ ] Remove test data properties to TestResultShape
  - [ ] Diagram
  - [ ] TAP
  - [ ] Tests
- [ ] RAP shape to use ceds: Competency class and properties.
  - [ ] Diagram
  - [ ] TAP
  - [ ] Tests
- [ ] new CourseAttribute shape.
  - [ ] Diagram
  - [ ] TAP
  - [ ] Tests
- [ ] LanguageShape to use ceds: PersonLanguage class, properties and code.
  - [ ] Diagram
  - [ ] TAP
  - [ ] Tests
