### ISSUE TITLE
Address mapping

### ISSUE THREAD

**Issue by philbarker** [pesc-org/json-ld-transcript#5]
CEDS addresses are too US specific and won't allow for PESC Transcript use in Canada or other countries.

Look at mapping Address to CTDL.

(Issue transferred from  https://github.com/philbarker/transcript_jsonld/issues/12)

**Comment by philbarker** [comment]
Suggested mapping to [CTDL Postal Address](https://credreg.net/ctdl/terms#PostalAddress) (which is quivalent to [schema.org](https://schema.org/PostalAddress))

| PESC | CTDL | CEDS |
|-------------------------------|-------------------------------|-------------------------------|
| | ceterms:postOfficeBoxNumber ||
| addressLine | ceterms:streetAddress
| city | ceterms:addressLocality
| stateProvinceCode | ceterms:addressRegion
| postalCode | ceterms:postalCode
| countryCode | ceterms:addressCountry | ceds:hasCountryCode
| effectiveDate | | ceds:RecordStartDate
| expirationDate | | ceds:RecordEndDate 
| attentionLine | |

**Comment by 4pins** [comment]
@philbarker So if this is the "suggested mapping" we will both have a place for the countryCode and have a relationship to a CEDS Country?

**Comment by philbarker** [comment]
@4pins Not yet decided, I was thinking more one or the other, they are pretty much equivalent.

**Comment by philbarker** [comment]
From today's call:
Use ceterms:addressCountry
Move RecordStartDateTime and RecordEndDateTime to Contact.
create pesc:attentionLine

**Comment by 4pins** [comment]
For what it is worth, today's decision makes sense to me.
